//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Checkout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Checkout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Checkout", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Shop Account.
        /// </summary>
        internal static string AccountModal_ActivateAccount {
            get {
                return ResourceManager.GetString("AccountModal_ActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (By activating account we will send you an activation email where you need to set a password in the store. After you log in you can come back to the ckeckout).
        /// </summary>
        internal static string AccountModal_ActivateAccountInstructions {
            get {
                return ResourceManager.GetString("AccountModal_ActivateAccountInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We see that you have an account with {0}, but you have no active account for {1}.
        /// </summary>
        internal static string AccountModal_ActivateAccountMessage {
            get {
                return ResourceManager.GetString("AccountModal_ActivateAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        internal static string AccountModal_Cancel {
            get {
                return ResourceManager.GetString("AccountModal_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already attached to an accaount.
        /// </summary>
        internal static string AccountModal_Header {
            get {
                return ResourceManager.GetString("AccountModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string AccountModal_Login {
            get {
                return ResourceManager.GetString("AccountModal_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We see that the email you have provided is associated with a {0} account already. Please log in or provide a different email!.
        /// </summary>
        internal static string AccountModal_LogInMessage {
            get {
                return ResourceManager.GetString("AccountModal_LogInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Account_InternationalAccountEnrollment {
            get {
                return ResourceManager.GetString("Account_InternationalAccountEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Account_InternationalAccountShopping {
            get {
                return ResourceManager.GetString("Account_InternationalAccountShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        internal static string Account_LanguageSelector {
            get {
                return ResourceManager.GetString("Account_LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string Account_PageTitle {
            get {
                return ResourceManager.GetString("Account_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Birthday.
        /// </summary>
        internal static string Account_YourBirthday {
            get {
                return ResourceManager.GetString("Account_YourBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apt building .
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Same As Shipping Address.
        /// </summary>
        internal static string AutoOrder_AddressSameAsShipping {
            get {
                return ResourceManager.GetString("AutoOrder_AddressSameAsShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to {0}.
        /// </summary>
        internal static string AutoOrder_AddToExisitingAutoOrder {
            get {
                return ResourceManager.GetString("AutoOrder_AddToExisitingAutoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Shipping Address.
        /// </summary>
        internal static string AutoOrder_AutoOrderShippingAddress {
            get {
                return ResourceManager.GetString("AutoOrder_AutoOrderShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string AutoOrder_Continue {
            get {
                return ResourceManager.GetString("AutoOrder_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Subscription.
        /// </summary>
        internal static string AutoOrder_CreateNewAutoOrder {
            get {
                return ResourceManager.GetString("AutoOrder_CreateNewAutoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string AutoOrder_Heading {
            get {
                return ResourceManager.GetString("AutoOrder_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often do you want to receive your subscription?.
        /// </summary>
        internal static string AutoOrder_HowOftenDoYouWantToRecieve {
            get {
                return ResourceManager.GetString("AutoOrder_HowOftenDoYouWantToRecieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Rundate:.
        /// </summary>
        internal static string AutoOrder_NextRunDate {
            get {
                return ResourceManager.GetString("AutoOrder_NextRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Setup.
        /// </summary>
        internal static string AutoOrder_PageTitle {
            get {
                return ResourceManager.GetString("AutoOrder_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting On.
        /// </summary>
        internal static string AutoOrder_StartingOn {
            get {
                return ResourceManager.GetString("AutoOrder_StartingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        internal static string BreadCrumb_Account {
            get {
                return ResourceManager.GetString("BreadCrumb_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string BreadCrumb_AutoOrder {
            get {
                return ResourceManager.GetString("BreadCrumb_AutoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string BreadCrumb_Cart {
            get {
                return ResourceManager.GetString("BreadCrumb_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Info.
        /// </summary>
        internal static string BreadCrumb_EnrollmentInfo {
            get {
                return ResourceManager.GetString("BreadCrumb_EnrollmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string BreadCrumb_Information {
            get {
                return ResourceManager.GetString("BreadCrumb_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string BreadCrumb_Payment {
            get {
                return ResourceManager.GetString("BreadCrumb_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string BreadCrumb_ShippingAddress {
            get {
                return ResourceManager.GetString("BreadCrumb_ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string BreadCrumb_ThankYou {
            get {
                return ResourceManager.GetString("BreadCrumb_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string Cart_AutoOrderTitle {
            get {
                return ResourceManager.GetString("Cart_AutoOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        internal static string Cart_Discounts {
            get {
                return ResourceManager.GetString("Cart_Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Cart_Frequency {
            get {
                return ResourceManager.GetString("Cart_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Cart Content.
        /// </summary>
        internal static string Cart_HideCartContent {
            get {
                return ResourceManager.GetString("Cart_HideCartContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Shipping Fee.
        /// </summary>
        internal static string Cart_InternationalShippingFee {
            get {
                return ResourceManager.GetString("Cart_InternationalShippingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Process Date.
        /// </summary>
        internal static string Cart_NextProcessDate {
            get {
                return ResourceManager.GetString("Cart_NextProcessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid With Points.
        /// </summary>
        internal static string Cart_PaidWithPoints {
            get {
                return ResourceManager.GetString("Cart_PaidWithPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string Cart_Shipping {
            get {
                return ResourceManager.GetString("Cart_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated at next step.
        /// </summary>
        internal static string Cart_ShippingCalculatedAtNextSTep {
            get {
                return ResourceManager.GetString("Cart_ShippingCalculatedAtNextSTep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cart Content.
        /// </summary>
        internal static string Cart_ShowCartContent {
            get {
                return ResourceManager.GetString("Cart_ShowCartContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string Cart_SubTotal {
            get {
                return ResourceManager.GetString("Cart_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Cart_Tax {
            get {
                return ResourceManager.GetString("Cart_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax calculated at next step.
        /// </summary>
        internal static string Cart_TaxCalculatedAtNextStep {
            get {
                return ResourceManager.GetString("Cart_TaxCalculatedAtNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Order.
        /// </summary>
        internal static string Cart_TodaysOrderTitle {
            get {
                return ResourceManager.GetString("Cart_TodaysOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Cart_Total {
            get {
                return ResourceManager.GetString("Cart_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone.
        /// </summary>
        internal static string Common_MobilePhone {
            get {
                return ResourceManager.GetString("Common_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string EnrollerSearch_Close {
            get {
                return ResourceManager.GetString("EnrollerSearch_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string EnrollerSearch_Edit {
            get {
                return ResourceManager.GetString("EnrollerSearch_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroller.
        /// </summary>
        internal static string EnrollerSearch_Enroller {
            get {
                return ResourceManager.GetString("EnrollerSearch_Enroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with the search.
        /// </summary>
        internal static string EnrollerSearch_Error {
            get {
                return ResourceManager.GetString("EnrollerSearch_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name or ID.
        /// </summary>
        internal static string EnrollerSearch_InputPlaceholder {
            get {
                return ResourceManager.GetString("EnrollerSearch_InputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without referral.
        /// </summary>
        internal static string EnrollerSearch_ModalClose {
            get {
                return ResourceManager.GetString("EnrollerSearch_ModalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for enroller.
        /// </summary>
        internal static string EnrollerSearch_ModalHeader {
            get {
                return ResourceManager.GetString("EnrollerSearch_ModalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not associated with any referral. Please search for your referral!.
        /// </summary>
        internal static string EnrollerSearch_ModalText {
            get {
                return ResourceManager.GetString("EnrollerSearch_ModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results from search.
        /// </summary>
        internal static string EnrollerSearch_NoResult {
            get {
                return ResourceManager.GetString("EnrollerSearch_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string EnrollmentInfo_ContinueButton {
            get {
                return ResourceManager.GetString("EnrollmentInfo_ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnrollmentInfo_EnrollerCheckboxText {
            get {
                return ResourceManager.GetString("EnrollmentInfo_EnrollerCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string EnrollmentInfo_LoginName {
            get {
                return ResourceManager.GetString("EnrollmentInfo_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Information.
        /// </summary>
        internal static string EnrollmentInfo_PageTitle {
            get {
                return ResourceManager.GetString("EnrollmentInfo_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnrollmentInfo_PoliciesCheckboxText {
            get {
                return ResourceManager.GetString("EnrollmentInfo_PoliciesCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Info.
        /// </summary>
        internal static string EnrollmentInfo_SectionHeader {
            get {
                return ResourceManager.GetString("EnrollmentInfo_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        internal static string EnrollmentInfo_TermsAndConditionsHeader {
            get {
                return ResourceManager.GetString("EnrollmentInfo_TermsAndConditionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;IMPORTANT INFORMATION: PLEASE READ&lt;/h3&gt;
        ///            &lt;p&gt;Before you may continue with your application, please review the Terms And Conditions of the Brand Partner Agreement and Policies and Procedures located below.&lt;/p&gt;
        ///            &lt;p&gt;
        ///                Once you have reviewed the Policies, and if you agree to abide by them, please click the &quot;I agree&quot; box located below and continue with your application to become an Independent Brand Partner. 
        ///                &lt;b&gt;PLEASE NOTE THAT BY CLICKING &quot;I AGREE&quot; YO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnrollmentInfo_TermsAndConditionsHtml {
            get {
                return ResourceManager.GetString("EnrollmentInfo_TermsAndConditionsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnrollmentInfo_WebsiteFeeCheckboxText {
            get {
                return ResourceManager.GetString("EnrollmentInfo_WebsiteFeeCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string Footer_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Footer_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Policy.
        /// </summary>
        internal static string Footer_RefundPolicy {
            get {
                return ResourceManager.GetString("Footer_RefundPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Policy.
        /// </summary>
        internal static string Footer_ShippingPolicy {
            get {
                return ResourceManager.GetString("Footer_ShippingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        internal static string Footer_TermsOfUse {
            get {
                return ResourceManager.GetString("Footer_TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Marketing.
        /// </summary>
        internal static string Information_AcceptMarketingLabel {
            get {
                return ResourceManager.GetString("Information_AcceptMarketingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        internal static string Information_AccountDetails {
            get {
                return ResourceManager.GetString("Information_AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Information_AddressHeading {
            get {
                return ResourceManager.GetString("Information_AddressHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string Information_AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("Information_AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Information_ContinueButton {
            get {
                return ResourceManager.GetString("Information_ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Information_LogIn {
            get {
                return ResourceManager.GetString("Information_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Same As this address.
        /// </summary>
        internal static string Information_ShoppingSameAsMain {
            get {
                return ResourceManager.GetString("Information_ShoppingSameAsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-sm-12&quot;&gt;
        ///                    &lt;h4&gt;The items has been added to your autoorder&lt;/h4&gt;
        ///                    &lt;div class=&quot;col-sm-6&quot;&gt;
        ///                        &lt;a href=&quot;{1}/account?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;margin-top:20px&quot;&gt;Go to subscription&lt;/a&gt;
        ///                    &lt;/div&gt;
        ///                    &lt;div class=&quot;col-sm-6&quot;&gt;
        ///                        &lt;a href=&quot;{1}?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderComplete_AddedToAutoOrderMessage {
            get {
                return ResourceManager.GetString("OrderComplete_AddedToAutoOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-sm-12&quot;&gt;
        ///                    &lt;h4&gt;Your autorder has been saved&lt;/h4&gt;
        ///                    &lt;div class=&quot;col-sm-6&quot;&gt;
        ///                        &lt;a href=&quot;{1}?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;margin-top:20px&quot;&gt;Go back to shop&lt;/a&gt;
        ///                    &lt;/div&gt;
        ///                    &lt;div class=&quot;col-sm-6&quot;&gt;
        ///                        &lt;a href=&quot;{1}/account?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;margin-top:20px&quot;&gt;Go [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderComplete_AutoOrderSavedMessage {
            get {
                return ResourceManager.GetString("OrderComplete_AutoOrderSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-sm-12&quot;&gt;
        ///                    &lt;h4&gt;Something went wrong.&lt;/h4&gt;&lt;p&gt;Please contact customer care!&lt;/p&gt;
        ///                    &lt;div class=&quot;col-sm-6&quot;&gt;
        ///                        &lt;a href=&quot;{0}?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;margin-top:20px&quot;&gt;Go back to shop&lt;/a&gt;
        ///                    &lt;/div&gt;
        ///                &lt;/div&gt;
        ///            &lt;/div&gt;.
        /// </summary>
        internal static string OrderComplete_FailedMessage {
            get {
                return ResourceManager.GetString("OrderComplete_FailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-sm-12&quot;&gt;
        ///                    &lt;h4&gt;Your payment was interupted.&lt;/h4&gt;&lt;p&gt;Please contact customer care if your order is not set to paid status withing 30 minutes or you have questions&lt;/p&gt;
        ///                    &lt;div class=&quot;col-sm-6&quot;&gt;
        ///                        &lt;a href=&quot;https://lordeandbelle.com/account?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;margin-top:20px&quot;&gt;Go to your account&lt;/a&gt;
        ///                    &lt;/div&gt;
        ///                    &lt;div cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderComplete_FailedMessageAccount {
            get {
                return ResourceManager.GetString("OrderComplete_FailedMessageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-12&quot;&gt;
        ///                &lt;h4&gt;Thank you for your order&lt;/h4&gt;&lt;p&gt;The payment process was interupted and did not finish properly. Please contact customer care to verify that it was successful. 
        ///To check the status of your order, please activate your account by clicking the button below, to get access to your customer account dashboard by setting a password.&lt;br/&gt;(Our system use several minutes to register the payment, so please allow some time for it to update)&lt;/p&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderComplete_FailedMessageToken {
            get {
                return ResourceManager.GetString("OrderComplete_FailedMessageToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-12&quot;&gt;
        ///                &lt;h4&gt;Thank you for your Registration&lt;/h4&gt;
        ///                &lt;p&gt;There is one last step for your account to be set up. Press the button below to activate your account!&lt;/p&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;col-sm-12&quot;&gt;
        ///                &lt;a href=&quot;{0}/account?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;margin-top:20px&quot;&gt;Log in to your account&lt;/a&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string OrderComplete_RegistrationCompletedMessage {
            get {
                return ResourceManager.GetString("OrderComplete_RegistrationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-sm-12&quot;&gt;
        ///                    &lt;h4&gt;Thank you for your order&lt;/h4&gt;
        ///                    &lt;div class=&quot;col-sm-6&quot;&gt;
        ///                        &lt;a href=&quot;{0}/account?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;margin-top:20px&quot;&gt;Go to your account&lt;/a&gt;
        ///                    &lt;/div&gt;
        ///                    &lt;div class=&quot;col-sm-6&quot;&gt;
        ///                        &lt;a href=&quot;{0}?clearcart=true&quot; class=&quot;btn btn-primary btn-block float-right&quot; style=&quot;margin-top:20px&quot;&gt;Go  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderComplete_ThankYouMessage {
            get {
                return ResourceManager.GetString("OrderComplete_ThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All transactions are encrypted and secure..
        /// </summary>
        internal static string Payments_AlltransactionsAreEncrypted {
            get {
                return ResourceManager.GetString("Payments_AlltransactionsAreEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address Same As Shipping.
        /// </summary>
        internal static string Payments_BillingAddressSameAsShipping {
            get {
                return ResourceManager.GetString("Payments_BillingAddressSameAsShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have provide invalid card credentials.
        /// </summary>
        internal static string Payments_CardInvalidMessage {
            get {
                return ResourceManager.GetString("Payments_CardInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardnumber.
        /// </summary>
        internal static string Payments_CardNumber {
            get {
                return ResourceManager.GetString("Payments_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditcard.
        /// </summary>
        internal static string Payments_CreditCard {
            get {
                return ResourceManager.GetString("Payments_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        internal static string Payments_CVV {
            get {
                return ResourceManager.GetString("Payments_CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string Payments_ExpirationDate {
            get {
                return ResourceManager.GetString("Payments_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many points.
        /// </summary>
        internal static string Payments_HowManyPoints {
            get {
                return ResourceManager.GetString("Payments_HowManyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name On Card.
        /// </summary>
        internal static string Payments_NameOnCard {
            get {
                return ResourceManager.GetString("Payments_NameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review &amp; Payment.
        /// </summary>
        internal static string Payments_PageTitle {
            get {
                return ResourceManager.GetString("Payments_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payments_PaymentHeading {
            get {
                return ResourceManager.GetString("Payments_PaymentHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with points.
        /// </summary>
        internal static string Payments_PayWithPointsHeading {
            get {
                return ResourceManager.GetString("Payments_PayWithPointsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string Payments_PlaceOrderButton {
            get {
                return ResourceManager.GetString("Payments_PlaceOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is being placed. Please Wait....
        /// </summary>
        internal static string Payments_PlacingOrderMessage {
            get {
                return ResourceManager.GetString("Payments_PlacingOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount entered is greater than current balance.
        /// </summary>
        internal static string Payments_PointAccountToHighAmountMessage {
            get {
                return ResourceManager.GetString("Payments_PointAccountToHighAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Balance.
        /// </summary>
        internal static string Payments_PointsBalance {
            get {
                return ResourceManager.GetString("Payments_PointsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipmethod.
        /// </summary>
        internal static string Payments_ShipmethodsHeading {
            get {
                return ResourceManager.GetString("Payments_ShipmethodsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wromg with shipping calculation.
        /// </summary>
        internal static string Payments_ShippingCalculationErrorMessage {
            get {
                return ResourceManager.GetString("Payments_ShippingCalculationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Points.
        /// </summary>
        internal static string Payments_UsePoints {
            get {
                return ResourceManager.GetString("Payments_UsePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship to this address.
        /// </summary>
        internal static string ShippingAddress_ContinueButton {
            get {
                return ResourceManager.GetString("ShippingAddress_ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new Address.
        /// </summary>
        internal static string ShippingAddress_NewAddressButton {
            get {
                return ResourceManager.GetString("ShippingAddress_NewAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string ShippingAddress_NewAddressHeading {
            get {
                return ResourceManager.GetString("ShippingAddress_NewAddressHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string ShippingAddress_PageTitle {
            get {
                return ResourceManager.GetString("ShippingAddress_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this address.
        /// </summary>
        internal static string ShippingAddress_SelectThisAddress {
            get {
                return ResourceManager.GetString("ShippingAddress_SelectThisAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streetaddress.
        /// </summary>
        internal static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string Summary_AutoOrder {
            get {
                return ResourceManager.GetString("Summary_AutoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting at:.
        /// </summary>
        internal static string Summary_AutoorderStartingAt {
            get {
                return ResourceManager.GetString("Summary_AutoorderStartingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Summary_Contact {
            get {
                return ResourceManager.GetString("Summary_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Summary_Edit {
            get {
                return ResourceManager.GetString("Summary_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To.
        /// </summary>
        internal static string Summary_ShipTo {
            get {
                return ResourceManager.GetString("Summary_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
